## Azure test
### Test protected page with valid Auth0 credentials
GET https://assign1app-bgfegmafbgh4caef.canadacentral-01.azurewebsites.net/protected
Authorization: Bearer YOUR_AUTH0_ACCESS_TOKEN
Accept: application/json

### Test protected page with invalid credentials
GET https://assign1app-bgfegmafbgh4caef.canadacentral-01.azurewebsites.net/protected
Content-Type: application/x-www-form-urlencoded
Accept: text/html



