## Azure test
### Test protected page with valid Auth0 credentials
GET https://assign1app-bgfegmafbgh4caef.canadacentral-01.azurewebsites.net/protected
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtaWxoc2lreG5sbnRhNHFqbC5jYS5hdXRoMC5jb20vIn0..ZafHckR7u7wLbxfa.n8OiiJ-JZShhsBLVxNumix497A0-RSwYDfXrzNnhqkyqRmdHYkfdxLuhC2mT0DoJDZLtlRV0z0MCdbsYsvhapqkISYCdyZ41ypvV5ujQLd1z-vDO7ufYesqxsJ5bq1L5IdVfKsjdSpYqMvKIsn1JgLpTLt20ALOR9lEll2W_zoQLFGclZ8527VReqsGdA9LhA4QQBQ5hwYYIKjlHWw1kVVHNnDOPKfXk8Z71PSWd4c0NSxs4tQFE6kDiN-rI7bM625LxOZV_N88cIudNiYVQ4PaqPx0pqf_QH9BfiUd2ZFvr6MxFphN_1Bu4nWHMdEzyPyEMi1ZP2o3-dWzrJb57Za0UBL3iuoY.6cSA-cysJJo2unN8gRkhuw
Accept: application/json

### Test protected page with invalid credentials
GET https://assign1app-bgfegmafbgh4caef.canadacentral-01.azurewebsites.net/protected
Content-Type: application/x-www-form-urlencoded
Accept: text/html



